"use client";

// 中央图标层：基于 lucide-react（SF Symbols 风格线性图标）
// 统一 strokeWidth / size，全站替换 emoji

import {
  Inbox,
  Send,
  Settings,
  Shield,
  Moon,
  Sun,
  Menu,
  LogOut,
  Mail,
  Copy,
  Trash2,
  Search,
  X,
  Check,
  AlertCircle,
  Info,
  Plus,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ArrowRight,
  ArrowLeft,
  KeyRound,
  Bot,
  Webhook,
  User,
  Download,
  Paperclip,
  Clock,
  Eye,
  EyeOff,
  Link2,
  Sparkles,
  Zap,
  Lock,
  Globe,
  RefreshCw,
  CircleCheck,
  CircleDot,
  Palette,
  MonitorSmartphone,
  Gift,
  Fingerprint,
  QrCode,
  Star,
  Heart,
  ExternalLink,
  MoreHorizontal,
  Loader2,
  CheckCircle2,
  Ban,
  Filter,
  SlidersHorizontal,
  Bell,
  BellRing,
  Bookmark,
  Archive,
  Tag,
  Ticket,
  Hash,
  AtSign,
  Server,
  Cloud,
  ShieldOff,
  Bug,
  Wrench,
  Languages,
  Database,
  Users,
  TrendingUp,
  Flame,
  Activity,
  Folder,
  FolderOpen,
  FileText,
  MessageSquare,
  Home,
  Package,
  Rocket,
  ShieldCheck,
  MapPin,
  Calendar,
  Timer,
  Power,
  Save,
  Pencil,
  List,
  Image,
  Bold,
  Italic,
  Code,
  Quote,
  SendHorizontal,
  Reply,
  ReplyAll,
  Share2,
  Smartphone,
  Wifi,
  Phone,
  BadgeCheck,
  CheckCheck,
  LogIn,
  HelpCircle,
  MailOpen,
  MailWarning,
  RotateCcw,
  Clock3,
  ListFilter,
  Mailbox,
  Settings2,
} from "lucide-react";

export type IconName =
  | "inbox" | "send" | "settings" | "shield" | "moon" | "sun" | "menu" | "logout"
  | "mail" | "copy" | "trash" | "search" | "x" | "check" | "alert" | "info" | "plus"
  | "chevron-right" | "chevron-left" | "chevron-down" | "arrow-right" | "arrow-left"
  | "key" | "bot" | "webhook" | "user" | "download" | "paperclip" | "clock" | "eye" | "eye-off"
  | "link" | "sparkles" | "zap" | "lock" | "globe" | "refresh" | "circle-check" | "circle-dot"
  | "palette" | "monitor" | "gift" | "fingerprint" | "qr" | "star" | "heart" | "external"
  | "more" | "loader" | "check-circle" | "ban" | "filter" | "sliders" | "bell" | "bell-ring"
  | "bookmark" | "archive" | "tag" | "ticket" | "hash" | "at-sign" | "server" | "cloud"
  | "shield-off" | "bug" | "wrench" | "languages" | "database" | "users" | "trending" | "flame"
  | "activity" | "folder" | "folder-open" | "file" | "message" | "home" | "package" | "rocket"
  | "shield-check" | "map-pin" | "calendar" | "timer" | "power" | "save" | "pencil" | "list"
  | "image" | "bold" | "italic" | "code" | "quote" | "send-h" | "reply" | "reply-all" | "share"
  | "smartphone" | "wifi" | "phone" | "badge-check" | "check-check" | "log-in" | "mail-open"
  | "mail-warning" | "rotate-ccw" | "clock-arrow" | "list-filter" | "mailbox" | "settings-2";

const iconMap: Record<IconName, any> = {
  inbox: Inbox,
  send: Send,
  settings: Settings,
  shield: Shield,
  moon: Moon,
  sun: Sun,
  menu: Menu,
  logout: LogOut,
  mail: Mail,
  copy: Copy,
  trash: Trash2,
  search: Search,
  x: X,
  check: Check,
  alert: AlertCircle,
  info: Info,
  plus: Plus,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  key: KeyRound,
  bot: Bot,
  webhook: Webhook,
  user: User,
  download: Download,
  paperclip: Paperclip,
  clock: Clock,
  eye: Eye,
  "eye-off": EyeOff,
  link: Link2,
  sparkles: Sparkles,
  zap: Zap,
  lock: Lock,
  globe: Globe,
  refresh: RefreshCw,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  palette: Palette,
  monitor: MonitorSmartphone,
  gift: Gift,
  fingerprint: Fingerprint,
  qr: QrCode,
  star: Star,
  heart: Heart,
  external: ExternalLink,
  more: MoreHorizontal,
  loader: Loader2,
  "check-circle": CheckCircle2,
  ban: Ban,
  filter: Filter,
  sliders: SlidersHorizontal,
  bell: Bell,
  "bell-ring": BellRing,
  bookmark: Bookmark,
  archive: Archive,
  tag: Tag,
  ticket: Ticket,
  hash: Hash,
  "at-sign": AtSign,
  server: Server,
  cloud: Cloud,
  "shield-off": ShieldOff,
  bug: Bug,
  wrench: Wrench,
  languages: Languages,
  database: Database,
  users: Users,
  trending: TrendingUp,
  flame: Flame,
  activity: Activity,
  folder: Folder,
  "folder-open": FolderOpen,
  file: FileText,
  message: MessageSquare,
  home: Home,
  package: Package,
  rocket: Rocket,
  "shield-check": ShieldCheck,
  "map-pin": MapPin,
  calendar: Calendar,
  timer: Timer,
  power: Power,
  save: Save,
  pencil: Pencil,
  list: List,
  image: Image,
  bold: Bold,
  italic: Italic,
  code: Code,
  quote: Quote,
  "send-h": SendHorizontal,
  reply: Reply,
  "reply-all": ReplyAll,
  share: Share2,
  smartphone: Smartphone,
  wifi: Wifi,
  phone: Phone,
  "badge-check": BadgeCheck,
  "check-check": CheckCheck,
  "log-in": LogIn,
  "mail-open": MailOpen,
  "mail-warning": MailWarning,
  "rotate-ccw": RotateCcw,
  "clock-arrow": Clock3,
  "list-filter": ListFilter,
  mailbox: Mailbox,
  "settings-2": Settings2,
};

export function Icon({
  name,
  size = 18,
  strokeWidth = 1.8,
  className,
  style,
}: {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
}) {
  const Cmp = iconMap[name] || HelpCircle;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} style={style} />;
}